CREATE DATABASE IF NOT EXISTS pong_db;
USE pong_db;
CREATE TABLE IF NOT EXISTS puntuaciones (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  rebotes INT NOT NULL,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);